import { Course } from "./course.types";

function randomDate(start: Date, end: Date) {
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  ).toISOString();
}

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "React for Beginners",
    description: "Learn the basics of React",
    level: "beginner",
    durationMinutes: 120,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "2",
    title: "Advanced TypeScript",
    description: "Deep dive into TypeScript features",
    level: "advanced",
    durationMinutes: 180,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "3",
    title: "Next.js Fundamentals",
    description: "Learn server-side rendering and routing",
    level: "intermediate",
    durationMinutes: 150,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "4",
    title: "JavaScript Essentials",
    description: "Core concepts and syntax of JS",
    level: "beginner",
    durationMinutes: 100,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "5",
    title: "Node.js Basics",
    description: "Introduction to Node.js and npm",
    level: "beginner",
    durationMinutes: 130,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "6",
    title: "Express.js Deep Dive",
    description: "Build robust APIs with Express",
    level: "intermediate",
    durationMinutes: 140,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "7",
    title: "MongoDB for Developers",
    description: "Learn document-based databases",
    level: "intermediate",
    durationMinutes: 160,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "8",
    title: "CSS Flexbox and Grid",
    description: "Layout techniques for modern web",
    level: "beginner",
    durationMinutes: 110,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "9",
    title: "Tailwind CSS Fundamentals",
    description: "Utility-first CSS framework",
    level: "beginner",
    durationMinutes: 90,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "10",
    title: "GraphQL Basics",
    description: "Query APIs efficiently",
    level: "intermediate",
    durationMinutes: 120,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "11",
    title: "Redux Essentials",
    description: "State management with Redux",
    level: "intermediate",
    durationMinutes: 130,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "12",
    title: "Vue.js Introduction",
    description: "Get started with Vue.js",
    level: "beginner",
    durationMinutes: 100,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "13",
    title: "Angular Crash Course",
    description: "Learn Angular basics",
    level: "beginner",
    durationMinutes: 120,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "14",
    title: "Svelte Fundamentals",
    description: "Modern JS framework basics",
    level: "beginner",
    durationMinutes: 90,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "15",
    title: "Python for Beginners",
    description: "Learn Python programming",
    level: "beginner",
    durationMinutes: 150,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "16",
    title: "Django Deep Dive",
    description: "Build web apps with Django",
    level: "intermediate",
    durationMinutes: 180,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "17",
    title: "Flask Basics",
    description: "Minimal Python web framework",
    level: "beginner",
    durationMinutes: 110,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "18",
    title: "Machine Learning 101",
    description: "Intro to ML concepts",
    level: "beginner",
    durationMinutes: 200,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "19",
    title: "Data Science with Python",
    description: "Analyze data using Python",
    level: "intermediate",
    durationMinutes: 170,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
  {
    id: "20",
    title: "Pandas and NumPy",
    description: "Python libraries for data",
    level: "intermediate",
    durationMinutes: 140,
    createdAt: randomDate(new Date(2024, 0, 1), new Date()),
  },
];
